# shellcheck shell=bash
# The ANY query (_probes/any.dns).

snapshot_any() {
    cmt "$domain: ANY"
    cmt "most servers answer RFC 8482 HINFO here rather than the full record"
    cmt "set; the per-type files in $APEX_DIR/ are the real answer"
    cmt "source: $source_desc"
    cmt "generated by dnsnap, do not edit"
    cmt ""
    "$DIG" @"$AUTH_NS" -t ANY -q "$domain" +norecurse "${DIG_OPTS[@]}" 2>/dev/null \
        | strip_noise | sort_sections
}
