# shellcheck shell=bash
# DS, DNSKEY, NSEC3PARAM and the validation verdict (_probes/dnssec.dns).

snapshot_dnssec() {
    cmt "$domain: DNSSEC"
    cmt "DS comes from the parent zone, DNSKEY from the apex; a zone that is"
    cmt "signed but has no DS is not validated by anyone. The two are filed"
    cmt "apart (DS in $PARENT_DIR/, DNSKEY in $APEX_DIR/) and read together here."
    cmt "generated by dnsnap, do not edit"
    cmt ""
    cmt "DS at the parent"
    # Same helper that writes $PARENT_DIR/DS.dns, so the two files cannot
    # drift apart.
    ask_parent "$domain" 43
    ds="$(printf '%s\n' "$PARENT_ANSWER" | awk '$3 == "IN" && $4 == "DS"' | records)"
    ds_source="$parent_source"
    if [ -n "$ds" ]; then
        printf '%s\n' "$ds"
        cmt "  from $ds_source"
    else
        cmt "  none: the delegation is unsigned"
        cmt "  asked: $ds_source"
    fi
    cmt ""
    cmt "DNSKEY at the apex"
    if ! dnskey="$(ask "$domain" 48 | records)"; then
        cmt "  QUERY FAILED: $AUTH_NS did not answer; not 'unsigned'"
    elif [ -n "$dnskey" ]; then printf '%s\n' "$dnskey"; else cmt "  none: the zone is unsigned"; fi
    cmt ""
    cmt "NSEC3PARAM at the apex"
    if ! nsec3="$(ask "$domain" 51 | records)"; then
        cmt "  QUERY FAILED: $AUTH_NS did not answer"
    elif [ -n "$nsec3" ]; then printf '%s\n' "$nsec3"; else cmt "  none"; fi
    cmt ""
    cmt "validation"
    # delv resolves the chain itself, so its verdict does not depend on
    # trusting the resolver. Both queries go through $PUBLIC_RESOLVER: a home
    # router that strips DNSSEC records would break the chain either way.
    if [ -n "$DELV" ]; then
        verdict="$("$DELV" @"$PUBLIC_RESOLVER" "$domain" A 2>&1 \
                     | grep -E '^(; (fully validated|unsigned answer|negative response)|;; resolution failed)' \
                     | head -1 | sed 's/^;* *//')"
        if [ -n "$verdict" ]; then
            cmt "  delv: $verdict"
        else
            cmt "  delv: no verdict (this build has no crypto support)"
        fi
    else
        cmt "  delv: not installed"
    fi
    flags="$("$DIG" @"$PUBLIC_RESOLVER" -t A -q "$domain" +dnssec +noall +comments "${DIG_OPTS[@]}" 2>/dev/null \
               | grep '^;; flags:' | head -1)"
    case "$flags" in
        "")       cmt "  $PUBLIC_RESOLVER: no answer" ;;
        *" ad;"*) cmt "  $PUBLIC_RESOLVER: AD set, serves this zone as authenticated" ;;
        *)        cmt "  $PUBLIC_RESOLVER: AD not set, not served as authenticated" ;;
    esac
}
