# shellcheck shell=bash
# The long tail of record types, swept into _apex/_extra.dns.

snapshot_extra_types() {
    cmt "$domain: remaining IANA record types"
    cmt "source: $source_desc"
    cmt "generated by dnsnap, do not edit"
    cmt ""
    empty=""
    unanswered=""
    for entry in $EXTRA_TYPES; do
        type="${entry%%:*}"
        code="${entry##*:}"
        # An unanswered type is kept out of the "no records" list, which
        # means the zone was asked and said nothing.
        if ! answer="$(ask "$domain" "$code" | records)"; then
            unanswered="$unanswered $type"
        elif [ -n "$answer" ]; then
            cmt "$type (type $code)"
            printf '%s\n\n' "$answer"
        else
            empty="$empty $type"
        fi
    done
    cmt "no records published for:$empty"
    if [ -n "$unanswered" ]; then
        cmt ""
        cmt "QUERY FAILED: $AUTH_NS did not answer for:$unanswered"
        cmt "nothing was learned about those types. See _meta.dns"
    fi
}
