# shellcheck shell=bash
# Names below the apex: one file each, in <domain>/_names/. Where the names
# come from is src/lib/discover.sh's problem; this file only asks.

# The apex is stripped off the front (the directory already says which domain
# this is) and the rest is laid out by domain_dir, so a name nests below its
# apex by the same rule that nests the apex below its parents. A label that is
# both a name and a path gets both: _domainkey.dns next to _domainkey/.
name_file_path() {
    printf '%s/%s/%s.dns' "$outdir" "$NAMES_DIR" "$(domain_dir "${1%".$domain"}")"
}

# What to ask a name for, as <TYPE>:<code> entries; see src/lib/config.sh.
name_types() {
    case "$1" in
        _*) printf '%s' "$UNDERSCORE_NAME_TYPES" ;;
        *)  printf '%s' "$NAME_TYPES" ;;
    esac
}

# render_name_file <name> <types asked> <records, or empty> <types unanswered>
render_name_file() {
    cmt "$1: a name below the apex of $domain"
    cmt "asked for: $2"
    cmt "source: $source_desc"
    # Old dig hands back RFC 3597 '\# len hex' for the types it cannot
    # decode, which below the apex is usually HTTPS or TLSA.
    if printf '%s\n' "$3" | awk '$3 == "IN" && $4 ~ /^TYPE[0-9]+$/ { hit = 1 }
                                 END { exit !hit }'; then
        cmt "some rdata below is RFC 3597 generic hex: this dig cannot decode"
        cmt "every type asked for. \`brew install bind\` for readable output"
    fi
    cmt "generated by dnsnap, do not edit"
    cmt ""
    if [ -n "$3" ]; then
        printf '%s\n' "$3"
    elif [ -z "$4" ]; then
        cmt "no records published"
    fi
    # A type nobody answered for is not a type with nothing in it, and a diff
    # must never let the two look alike.
    if [ -n "$4" ]; then
        cmt ""
        cmt "QUERY FAILED: $AUTH_NS did not answer for: $4"
        cmt "nothing was learned about those. See _meta.dns"
    fi
}

snapshot_names() {
    mkdir -p "$outdir/$NAMES_DIR"

    # $NAMES is filled by snapshot() before this runs, because discovery reads
    # the files about to be rewritten.
    for name in $NAMES; do
        asked=""
        found=""
        unanswered=""
        for entry in $(name_types "$name"); do
            asked="$asked ${entry%%:*}"
            if ! one="$(ask "$name" "${entry##*:}")"; then
                unanswered="$unanswered ${entry%%:*}"
                continue
            fi
            found="$found$one
"
        done
        found="$(printf '%s' "$found" | records)"
        name_file="$(name_file_path "$name")"
        # The grouping directories a middle label asks for.
        mkdir -p "$(dirname "$name_file")"
        render_name_file "$name" "${asked# }" "$found" "${unanswered# }" > "$name_file"
    done
}
