# shellcheck shell=bash
# Each authoritative nameserver's own view (_probes/nameservers.dns).

snapshot_nameservers() {
    cmt "$domain: authoritative nameservers"
    cmt "each server's own addresses and the SOA serial it is serving;"
    cmt "serials that disagree mean the zone has not finished propagating"
    cmt ""
    cmt "0x20 and cookie are properties of the server, not of the zone, so"
    cmt "each is asked separately: whether a mixed-case query name comes back"
    cmt "untouched, and whether the server sends a DNS cookie (RFC 7873) of"
    cmt "its own. The cookie is a fresh nonce every query, so only its size"
    cmt "is recorded, never its value."
    cmt "generated by dnsnap, do not edit"
    cmt ""
    if [ -z "$nameservers" ]; then
        cmt "no NS records found"
    fi
    probe="$(mixed_case "$domain")"
    for ns in $nameservers; do
        cmt "$ns"
        "$DIG" @"$PUBLIC_RESOLVER" +short -t A -q "$ns" "${DIG_OPTS[@]}" 2>/dev/null | LC_ALL=C sort | sed 's/^/;;   A     /'
        "$DIG" @"$PUBLIC_RESOLVER" +short -t AAAA -q "$ns" "${DIG_OPTS[@]}" 2>/dev/null | LC_ALL=C sort | sed 's/^/;;   AAAA  /'
        serial="$("$DIG" @"$ns" -t SOA -q "$domain" +noall +answer +norecurse "${DIG_OPTS[@]}" 2>/dev/null | records | awk '{print $7}')"
        if [ -n "$serial" ]; then cmt "  serial $serial"; else cmt "  serial unreachable"; fi

        # dig sends the name exactly as written and prints the question
        # section of the reply, so the two are directly comparable.
        echoed="$("$DIG" @"$ns" -t TYPE6 -q "$probe" +noall +question +norecurse "${DIG_OPTS[@]}" 2>/dev/null \
                    | sed -n 's/^;\([^[:space:]]*\).*/\1/p' | head -1 | sed 's/\.$//')"
        if [ -z "$echoed" ]; then
            cmt "  0x20   no answer"
        elif [ "$echoed" = "$probe" ]; then
            cmt "  0x20   case preserved ($probe)"
        else
            cmt "  0x20   case changed: sent $probe, got $echoed"
        fi

        # A client cookie is 8 bytes; anything past those 16 hex digits is
        # the server's own, which is the half that does the work.
        cookie="$("$DIG" @"$ns" -t TYPE6 -q "$domain" +cookie +norecurse "${DIG_OPTS[@]}" 2>/dev/null \
                    | sed -n 's/^; COOKIE: \([0-9a-fA-F]*\).*/\1/p' | head -1)"
        cookie_len="$(printf '%s' "$cookie" | wc -c | tr -d ' ')"
        if [ "$cookie_len" -eq 0 ]; then
            cmt "  cookie none returned"
        elif [ "$cookie_len" -le 16 ]; then
            cmt "  cookie client cookie echoed, none of its own"
        else
            cmt "  cookie server cookie, $(( (cookie_len - 16) / 2 )) bytes"
        fi
        cmt ""
    done
}
