# shellcheck shell=bash
# What the zone says when it has nothing to say (_probes/negative.dns).

# Two queries that record how the zone refuses: a name that is not in it, and
# a type the apex cannot hold (a CNAME cannot sit beside the SOA, so this is a
# NODATA answer by construction). Both answers live in the header and the
# authority section rather than the answer section.
snapshot_negative() {
    cmt "$domain: negative answers"
    cmt "a name that does not exist, and a type that does not exist at a"
    cmt "name that does. Read the status line first: NXDOMAIN is the plain"
    cmt "answer, while NOERROR with an empty answer section means a wildcard"
    cmt "caught it or the zone signs its denials the Cloudflare way. The SOA"
    cmt "below sets the negative TTL."
    cmt "signatures omitted: an RRSIG expires and is reissued on its own"
    cmt "source: $source_desc"
    cmt "generated by dnsnap, do not edit"
    cmt ""
    cmt "$NXDOMAIN_PROBE.$domain/A: a name that should not be there"
    cmt ""
    ask_msg "$NXDOMAIN_PROBE.$domain" 1 | negative_view
    cmt ""
    cmt "$domain/CNAME: a type the apex cannot hold (NODATA)"
    cmt ""
    ask_msg "$domain" 5 | negative_view
}
