# shellcheck shell=bash
# The delegation: what the parent zone publishes about this domain (_parent/).
#
# Asked of a server authoritative for the parent and of nowhere else. A cached
# DS is not the DS the registry publishes, and its TTL counts down between
# runs, rewriting the file for no reason.

# parent_ns <domain>. One server authoritative for the zone above it. The
# public resolver only finds it; from there the questions go direct.
parent_ns() {
    "$DIG" @"$PUBLIC_RESOLVER" +short -t NS -q "${1#*.}" "${DIG_OPTS[@]}" 2>/dev/null \
        | sed 's/\.$//' | grep -v '^$' | LC_ALL=C sort | head -1
}

# ask_parent <domain> <typecode>. The referral as the parent gives it. The
# records are in the authority section, not the answer: the parent is saying
# where to go, not answering. +norecurse keeps it from being chased for us.
#
# Success turns on whether the server replied, not on whether records came
# back: a parent answering "no DS" is telling us the delegation is unsigned.
#
# Sets $PARENT_ANSWER and $parent_source rather than printing, because which
# server answered is half the answer and a $(...) would lose it.
ask_parent() {
    if [ -z "$PARENT_NS" ]; then
        note_query_failure "${1#*.}: no nameserver found for the parent of $1"
        PARENT_ANSWER=""
        parent_source="nothing answered"
        return 1
    fi
    msg="$("$DIG" @"$PARENT_NS" -t "TYPE$2" -q "$1" \
                 +noall +comments +answer +authority +norecurse "${DIG_OPTS[@]}" 2>/dev/null)"
    rc=$?
    if ! answered "$rc" "$msg"; then
        note_query_failure "$1 TYPE$2 at the parent: no answer from $PARENT_NS"
        PARENT_ANSWER=""
        parent_source="nothing answered"
        return 1
    fi
    parent_source="$PARENT_NS (authoritative for ${1#*.})"
    PARENT_ANSWER="$(printf '%s\n' "$msg" | sed '/^;/d')"
}

snapshot_parent() {
mkdir -p "$outdir/$PARENT_DIR"
for entry in $PARENT_TYPES; do
    type="${entry%%:*}"
    code="${entry##*:}"
    # The referral carries the NS set and, when signed, the DS beside it.
    # Anything else in there (an SOA on a negative answer, the NSEC proving
    # the DS is absent) is about the parent, not about us.
    ask_parent "$domain" "$code"
    answer="$(printf '%s\n' "$PARENT_ANSWER" | awk -v t="$type" '$3 == "IN" && $4 == t' | records)"
    {
        cmt "$domain: $type at the parent (type $code)"
        cmt "source: $parent_source"
        cmt "the delegation, not the zone's own answer; its copy of $type, if"
        cmt "it publishes one, is in $APEX_DIR/"
        cmt "generated by dnsnap, do not edit"
        cmt ""
        if [ -n "$answer" ]; then
            printf '%s\n' "$answer"
        elif [ "$type" = "DS" ]; then
            cmt "no DS: the delegation is unsigned"
        else
            cmt "no records published"
        fi
    } > "$outdir/$PARENT_DIR/$type.dns"
done

{
    cmt "$domain: glue at the parent"
    cmt "the addresses the parent hands out with the referral. for a nameserver"
    cmt "inside this zone they are the only way in; anywhere else they are a"
    cmt "shortcut at best, and often absent"
    cmt "generated by dnsnap, do not edit"
    cmt ""
    glue=""
    if [ -n "$PARENT_NS" ]; then
        glue="$("$DIG" @"$PARENT_NS" -t NS -q "$domain" +noall +additional +norecurse "${DIG_OPTS[@]}" 2>/dev/null \
                  | awk '$3 == "IN" && ($4 == "A" || $4 == "AAAA")' | records)"
    fi
    if [ -n "$glue" ]; then
        printf '%s\n' "$glue"
    else
        cmt "none published"
    fi
} > "$outdir/$PARENT_DIR/_glue.dns"
}
