# shellcheck shell=bash
# Reverse DNS for the addresses the zone publishes (_probes/reverse.dns).

snapshot_reverse() {
    cmt "$domain: reverse DNS for the addresses this zone publishes"
    cmt "these PTRs belong to the hosting provider, not to this domain"
    cmt "generated by dnsnap, do not edit"
    cmt ""
    # The apex's own addresses, and every address a name below it publishes.
    addresses="$({ cat "$outdir/$APEX_DIR/A.dns" "$outdir/$APEX_DIR/AAAA.dns" 2>/dev/null
                   find "$outdir/$NAMES_DIR" -type f -name '*.dns' \
                        -exec cat {} + 2>/dev/null
                 } | awk '$1 !~ /^;/ && ($4 == "A" || $4 == "AAAA") { print $5 }' \
                   | LC_ALL=C sort -u)"
    if [ -z "$addresses" ]; then
        cmt "no addresses published"
    fi
    for address in $addresses; do
        ptr="$("$DIG" @"$PUBLIC_RESOLVER" +short -x "$address" "${DIG_OPTS[@]}" 2>/dev/null | LC_ALL=C sort | tr '\n' ' ')"
        if [ -n "$ptr" ]; then
            printf ';; %-39s %s\n' "$address" "$ptr"
        else
            printf ';; %-39s %s\n' "$address" "(no PTR)"
        fi
    done
}
