# shellcheck shell=bash
# Delegation path from the root (_probes/trace.dns).

# TTLs are blanked, RRSIGs and "received from" lines dropped and each hop
# sorted: which root server answered, and in what order, is random and would
# otherwise rewrite this file every run.
snapshot_trace() {
    cmt "$domain: delegation path from the root"
    cmt "TTLs blanked and signatures omitted: this is the chain of"
    cmt "delegations, not a loadable zone"
    cmt "generated by dnsnap, do not edit"
    cmt ""
    # +trace has to start somewhere that will talk to the root, which the
    # domain's own servers will not.
    trace="$("$DIG" @"$PUBLIC_RESOLVER" -q "$domain" +trace "${DIG_OPTS[@]}" 2>/dev/null)"
    if [ "$(printf '%s' "$trace" | grep -c '[[:space:]]NS[[:space:]]')" -lt 2 ]; then
        note_query_failure "+trace for $domain: no delegation path from $PUBLIC_RESOLVER"
    fi
    printf '%s\n' "$trace" | strip_noise \
        | drop_signatures \
        | grep -v '^;; Received' \
        | awk 'BEGIN { OFS = "\t" } { if ($2 ~ /^[0-9]+$/ && $3 == "IN") $2 = "-"; print }' \
        | sort_sections
}
