# shellcheck shell=bash
# One file per primary record type the apex answers for (_apex/<TYPE>.dns).
# The delegation's own records are in parent.sh.

snapshot_types() {
mkdir -p "$outdir/$APEX_DIR"
for entry in $PRIMARY_TYPES; do
    type="${entry%%:*}"
    code="${entry##*:}"
    # pipefail carries ask()'s failure through `| records`, so an unanswered
    # query is told apart from an answered one that is empty.
    if answer="$(ask "$domain" "$code" | records)"; then got_answer="yes"; else got_answer=""; fi
    {
        cmt "$domain: $type (type $code)"
        cmt "source: $source_desc"
        case "$answer" in
            *"TYPE$code"*)
                cmt "rdata below is RFC 3597 generic hex: this dig cannot"
                cmt "decode $type. \`brew install bind\` for readable output" ;;
        esac
        cmt "generated by dnsnap, do not edit"
        cmt ""
        if [ -z "$got_answer" ]; then
            cmt "QUERY FAILED: $AUTH_NS did not answer"
            cmt "not an empty record set: nothing was learned. See _meta.dns"
        elif [ -n "$answer" ]; then
            printf '%s\n' "$answer"
        else
            cmt "no records published"
        fi
    } > "$outdir/$APEX_DIR/$type.dns"
done
}
