# shellcheck shell=bash
# Registry whois (whois.dns). Sets whois_note.

snapshot_whois() {
whois_note="not attempted"
if command -v whois >/dev/null 2>&1; then
    tld="${domain##*.}"
    whois_server="$(whois -h whois.iana.org "$tld" 2>/dev/null | awk '/^whois:/ { print $2; exit }')"
    if [ -n "$whois_server" ]; then
        whois_out="$(whois -h "$whois_server" "$domain" 2>/dev/null)"
    else
        whois_out="$(whois "$domain" 2>/dev/null)"
    fi
    # Some registries still answer in ISO-8859-1 (registro.br does), and those
    # bytes make the file invalid UTF-8, at which point grep treats it as
    # binary. Re-encode whatever does not already parse.
    if command -v iconv >/dev/null 2>&1 \
       && ! printf '%s' "$whois_out" | iconv -f UTF-8 -t UTF-8 >/dev/null 2>&1; then
        whois_out="$(printf '%s' "$whois_out" | iconv -f ISO-8859-1 -t UTF-8 2>/dev/null \
                       || printf '%s' "$whois_out")"
    fi
    # Besides the usual "last update" stamp, some registries echo the time of
    # the query and the address it came from, which is the machine running
    # this script, not the domain.
    whois_out="$(printf '%s' "$whois_out" | sed -E \
                   -e '/Last update of/d' \
                   -e '/^%[[:space:]]*[0-9]{4}-[0-9]{2}-[0-9]{2}T/d' \
                   -e 's/[[:space:]]*$//')"
    if printf '%s' "$whois_out" | grep -qiF "$domain" \
       && ! printf '%s' "$whois_out" | grep -q '^% IANA WHOIS server'; then
        {
            cmt "$domain: registry whois${whois_server:+ ($whois_server)}"
            cmt "rdap.json is the structured version of the same data"
            cmt "generated by dnsnap, do not edit"
            cmt ""
            printf '%s\n' "$whois_out"
        } > "$outdir/whois.dns"
        whois_note="ok${whois_server:+ via $whois_server}"
    else
        whois_note="no domain-level whois for .$tld (RDAP only)"
    fi
fi
}
